@protocolver = HTTP/1.1
@protocol    = http
@hostname    = localhost
@port        = 8099
@url         = {{protocol}}://{{hostname}}:{{port}}


@date = {{$datetime "YYYY-MM-DDThh:mm:ss"}}Z

@template_uuid = 00000000000000000000000000000001
@command_uuid = 00000000000000000000000000000001

//<<<< GET >>>> 
# @name get_template_command

GET {{url}}/server/template/{{template_uuid}}/command/{{command_uuid}}  {{protocolver}}
content-type: application/json

###
# @name list_template_command

GET {{url}}/server/template/{{template_uuid}}/command  {{protocolver}}
content-type: application/json

###
# @name get_template

GET {{url}}/server/template/{{template_uuid}}  {{protocolver}}
content-type: application/json

###
# @name find_template__match__uuid


@match_uuid = (eq uuid "{{template_uuid}}")

GET {{url}}/server/template?q={{match_uuid}}  {{protocolver}}
content-type: application/json

###