// Code generated by Ice-cream-maker DO NOT EDIT.
package service
 
func (Service) ColumnNames() []string {
	return []string{
 		"pdate",
 		"cluster_uuid",
 		"uuid",
 		"name",
 		"summary",
 		"template_uuid",
 		"flow",
 		"inputs",
 		"step_max",
 		"subscribed_channel",
 		"priority",
 		"created",
	}
}
 
func (ServiceResult) ColumnNames() []string {
	return []string{
 		"pdate",
 		"cluster_uuid",
 		"uuid",
 		"created",
 		"result_type",
 		"result",
	}
}
 
func (ServiceStatus) ColumnNames() []string {
	return []string{
 		"pdate",
 		"cluster_uuid",
 		"uuid",
 		"created",
 		"step_max",
 		"step_seq",
 		"status",
 		"started",
 		"ended",
 		"message",
	}
}
 
func (Service_polling) ColumnNames() []string {
	return []string{
 		"pdate",
 		"cluster_uuid",
 		"uuid",
 		"created",
 		"priority",
	}
}
 
func (row Service) Values() []interface{} {
	return []interface{}{
		row.PartitionDate,
		row.ClusterUuid,
		row.Uuid,
		row.Name,
		row.Summary,
		row.TemplateUuid,
		row.Flow,
		row.Inputs,
		row.StepMax,
		row.SubscribedChannel,
		row.Priority,
		row.Created,
	}
}
 
func (row ServiceResult) Values() []interface{} {
	return []interface{}{
		row.PartitionDate,
		row.ClusterUuid,
		row.Uuid,
		row.Created,
		row.ResultSaveType,
		row.Result,
	}
}
 
func (row ServiceStatus) Values() []interface{} {
	return []interface{}{
		row.PartitionDate,
		row.ClusterUuid,
		row.Uuid,
		row.Created,
		row.StepMax,
		row.StepSeq,
		row.Status,
		row.Started,
		row.Ended,
		row.Message,
	}
}
 
func (row Service_polling) Values() []interface{} {
	return []interface{}{
		row.PartitionDate,
		row.ClusterUuid,
		row.Uuid,
		row.Created,
		row.Priority,
	}
}

type Scanner interface {
	Scan(dest ...interface{}) error
}
 
func (row *Service) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.TemplateUuid,
		&row.Flow,
		&row.Inputs,
		&row.StepMax,
		&row.SubscribedChannel,
		&row.Priority,
		&row.Created,
	)
}
 
func (row *ServiceResult) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Created,
		&row.ResultSaveType,
		&row.Result,
	)
}
 
func (row *ServiceStatus) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Created,
		&row.StepMax,
		&row.StepSeq,
		&row.Status,
		&row.Started,
		&row.Ended,
		&row.Message,
	)
}
 
func (row *Service_polling) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Created,
		&row.Priority,
	)
}
 
func (row *Service) Ptrs() []interface{} {
	return []interface{}{
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.TemplateUuid,
		&row.Flow,
		&row.Inputs,
		&row.StepMax,
		&row.SubscribedChannel,
		&row.Priority,
		&row.Created,
	}
}
 
func (row *ServiceResult) Ptrs() []interface{} {
	return []interface{}{
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Created,
		&row.ResultSaveType,
		&row.Result,
	}
}
 
func (row *ServiceStatus) Ptrs() []interface{} {
	return []interface{}{
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Created,
		&row.StepMax,
		&row.StepSeq,
		&row.Status,
		&row.Started,
		&row.Ended,
		&row.Message,
	}
}
 
func (row *Service_polling) Ptrs() []interface{} {
	return []interface{}{
		&row.PartitionDate,
		&row.ClusterUuid,
		&row.Uuid,
		&row.Created,
		&row.Priority,
	}
}
