// Code generated by Ice-cream-maker DO NOT EDIT.
package v3
 
func (Cluster) ColumnNames() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"polling_option",
 		"polling_limit",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (row Cluster) Values() []interface{} {
	return []interface{}{
		row.ID,
		row.Uuid,
		row.Name,
		row.Summary,
		row.PollingOption,
		row.PoliingLimit,
		row.Created,
		row.Updated,
		row.Deleted,
	}
}

type Scanner interface {
	Scan(dest ...interface{}) error
}
 
func (row *Cluster) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.ID,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.PollingOption,
		&row.PoliingLimit,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	)
}
 
func (row *Cluster) Ptrs() []interface{} {
	return []interface{}{
		&row.ID,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.PollingOption,
		&row.PoliingLimit,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	}
}
