variables:
  DOCKER_DRIVER: overlay
  APP_DOCKERFILE_LOCATION: "Dockerfile"
  APP_IMAGE_NAME: "nexclipper-sudory"
  APP_VERSION: "0.2.74"

default:
  services:
    - docker:dind
  tags:
    - gitlab-runner-k8s
  retry: 2
  image: docker:latest


stages:
  - build-code
  - dev
  - stg

code-build-server:
  image: golang:1.18.1-alpine3.15
  stage: build-code
  before_script:
    - apk add --no-cache make git
    - go get -v -u github.com/swaggo/swag/cmd/swag
    - make prep 
    - make swagger
  script:
    - make go-build target=server
  artifacts:
    paths:
      - bin/
      - pkg/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "staging" ||  $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-sudory-server-dev:
  stage: dev
  before_script:
    - "apk add --no-cache git"
  variables:
    BUILD_TARGET_STAGE: build-stage
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_DOCKERFILE_LOCATION: "Dockerfile.server"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - "source /data/scripts/build_v3.sh $APP_IMAGE_NAME"
  needs:
    - job: code-build-server
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

deploy-nexclipper-sudory-server-dev:
  stage: dev
  image: repo.nexclipper.io/nexclipper/helm-kubectl:latest
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh dev
  script:
    - "source /data/scripts/deploy_v3.sh dev sudory"
  needs:
    - job: docker-build-sudory-server-dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
      when: manual


docker-build-sudory-server-stg:
  stage: stg
  before_script:
    - "apk add --no-cache git"
  variables:
    BUILD_TARGET_STAGE: build-stage
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper"
    APP_DOCKERFILE_LOCATION: "Dockerfile.server"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - "source /data/scripts/build_v3.sh $APP_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"

deploy-nexclipper-sudory-server-stg:
  stage: stg
  image: repo.nexclipper.io/nexclipper/helm-kubectl:latest
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name nxc-prd-01
  script:
   - "source /data/scripts/deploy_v3.sh stg sudory"
  needs:
    - job: docker-build-sudory-server-stg
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"


code-build-client:
  image: golang:1.18.1-alpine3.15
  stage: build-code
  before_script:
    - apk add --no-cache make git
    - go get -v -u github.com/swaggo/swag/cmd/swag
    - make prep 
    - make swagger
  script:
    - make go-build target=client
  artifacts:
    paths:
      - bin/
      - pkg/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-sudory-client-dev:
  stage: dev
  before_script:
    - "apk add --no-cache git"
  variables:
    BUILD_TARGET_STAGE: build-stage
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_DOCKERFILE_LOCATION: "Dockerfile.client"
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  needs:
    - job: code-build-client
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - "source /data/scripts/build_v3.sh $APP_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-sudory-client-stg:
  stage: stg
  before_script:
    - "apk add --no-cache git"
  variables:
    BUILD_TARGET_STAGE: build-stage
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper"
    APP_DOCKERFILE_LOCATION: "Dockerfile.client"
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  needs:
    - job: code-build-client
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - "source /data/scripts/build_v3.sh $APP_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"


# deploy-nexclipper-sudory-client-dev:
#   stage: dev
#   image: repo.nexclipper.io/nexclipper/helm-kubectl:latest
#   variables:
#     HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
#     APP_IMAGE_NAME: "nexclipper-sudory-client"
#   before_script:
#     - echo -e "\nLogin to Kubernetes"
#     - source /data/scripts/login-cluster.sh dev
#   script:
#     - echo "Retrieve uuid and token for sudory client"
#     - "source kube/getClientToken.sh $S_SERVER_URL"
#     - "source /data/scripts/deploy_v3.sh dev sudory"
#   needs:
#     - job: docker-build-sudory-client-dev
#   rules:
#     - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
#       when: manual
#   allow_failure: true
