variables:
  APP_IMAGE_NAME: "nexclipper-sudory"
  APP_VERSION: "0.2.84"

default:
  tags:
    - gitlab-runner-k8s
  retry: 2


stages:
  - build-code
  - dev
  - stg

code-build-server:
  image: golang:1.18.1-alpine3.15
  stage: build-code
  before_script:
    - apk add --no-cache make git
    - go get -v -u github.com/swaggo/swag/cmd/swag
    - make prep 
    - make swagger
  script:
    - make go-build target=server
  artifacts:
    paths:
      - bin/
      - pkg/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "staging" ||  $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-commit-sudory-server:
  stage: build-code
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASS\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --target "common-build-stage"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.server"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${CI_COMMIT_SHORT_SHA}"
  needs:
    - code-build-server
  rules:
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

deploy-nexclipper-sudory-server-commit:
  stage: dev
  image: repo.nexclipper.io/nexclipper/helm-kubectl:latest
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh dev
  script:
    - "source /data/scripts/deploy.sh dev sudory"
  needs: 
    - job: docker-build-commit-sudory-server
  rules:
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
      when: manual


docker-build-sudory-server-dev:
  stage: dev
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASS\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --target "common-build-stage"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.server"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${APP_VERSION}"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:latest"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${CI_COMMIT_SHORT_SHA}"
  needs:
    - job: code-build-server
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"

deploy-nexclipper-sudory-server-dev:
  stage: dev
  image: repo.nexclipper.io/nexclipper/helm-kubectl:latest
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh dev
  script:
    - "source /data/scripts/deploy.sh dev sudory"
  needs: 
    - job: docker-build-sudory-server-dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'


docker-build-sudory-server-stg:
  stage: stg
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASS\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --target "common-build-stage"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.server"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${APP_VERSION}"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:latest"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${CI_COMMIT_SHORT_SHA}"
  needs:
    - job: code-build-server
  rules:
    - if: $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

deploy-nexclipper-sudory-server-stg:
  stage: stg
  image: repo.nexclipper.io/nexclipper/helm-kubectl:latest
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh stg
  script:
   - "source /data/scripts/deploy.sh stg sudory"
  needs:
    - job: docker-build-sudory-server-stg
  rules:
    - if: $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/


code-build-client:
  image: golang:1.18.1-alpine3.15
  stage: build-code
  before_script:
    - apk add --no-cache make git
    - go get -v -u github.com/swaggo/swag/cmd/swag
    - make prep 
    - make swagger
  script:
    - make go-build target=client
  artifacts:
    paths:
      - bin/
      - pkg/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-commit-sudory-client:
  stage: build-code
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASS\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --target "common-build-stage"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.client"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${CI_COMMIT_SHORT_SHA}"
  needs:
    - job: code-build-client
  rules:
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-sudory-client-dev:
  stage: dev
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper-dev"
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASS\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --target "common-build-stage"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.client"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${APP_VERSION}"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:latest"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${CI_COMMIT_SHORT_SHA}"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" 

docker-build-sudory-client-stg:
  stage: stg
  variables:
    HARBOR_NEXCLIPPER_PROJECT: "nexclipper"
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME\":{\"username\":\"$HARBOR_USER\",\"password\":\"$HARBOR_PASS\"}}}" > /kaniko/.docker/config.json
  script:
    - echo "building docker image for $APP_IMAGE_NAME "
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --target "common-build-stage"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.client"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${APP_VERSION}"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:latest"
      --destination "$HARBOR_URL/$HARBOR_NEXCLIPPER_PROJECT/$APP_IMAGE_NAME:${CI_COMMIT_SHORT_SHA}"
  needs:
    - job: code-build-client
  rules:
    - if: $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

