variables:
  DOCKER_DRIVER: overlay
  APP_DOCKERFILE_LOCATION: "Dockerfile"
  APP_IMAGE_NAME: "nexclipper-sudory"

default:
  services:
    - docker:dind
  tags:
    - nexclipper
  retry: 2
  image: docker:latest

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - bin/
#     - pkg/

stages:
  - build
  - package
  - deploy-dev

code-build-server:
  image: golang:1.18.1-alpine3.15
  stage: build
  before_script:
    - apk add --no-cache make git
    - go get -v -u github.com/swaggo/swag/cmd/swag
    - make prep 
    - go mod tidy
    - make swagger
  script:
    - make go-build target=server
  artifacts:
    paths:
      - bin/
      - pkg/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

code-build-client:
  image: golang:1.18.1-alpine3.15
  stage: build
  before_script:
    - apk add --no-cache make git
    - go get -v -u github.com/swaggo/swag/cmd/swag
    - make prep 
    - go mod tidy
    - make swagger
  script:
    - make go-build target=client
  artifacts:
    paths:
      - bin/
      - pkg/
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/


docker-build-sudory-server:
  stage: package
  before_script:
    - "apk add --no-cache git"
  variables:
    APP_DOCKERFILE_LOCATION: "Dockerfile.server"
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  script:
    - echo "\nBuild docker image for $APP_IMAGE_NAME"
    - "source /data/scripts/build_v2.sh $APP_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/

docker-build-sudory-client:
  stage: package
  before_script:
    - "apk add --no-cache git"
  variables:
    APP_DOCKERFILE_LOCATION: "Dockerfile.client"
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  script:
    - echo "\nBuild docker image for $APP_IMAGE_NAME"
    - "source /data/scripts/build_v2.sh $APP_IMAGE_NAME"
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/


deploy-nexclipper-sudory-server:
  stage: deploy-dev
  image: dtzar/helm-kubectl:latest
  variables:
    APP_IMAGE_NAME: "nexclipper-sudory-server"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh dev
  script:
    - "source /data/scripts/deploy_v2.sh dev sudory"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
      when: manual

deploy-nexclipper-sudory-client:
  stage: deploy-dev
  image: dtzar/helm-kubectl:latest
  variables:
    APP_IMAGE_NAME: "nexclipper-sudory-client"
  before_script:
    - echo -e "\nLogin to Kubernetes"
    - source /data/scripts/login-cluster.sh dev
  script:
    - echo "Retrieve uuid and token for sudory client"
    - "source kube/getClientToken.sh $S_SERVER_URL"
    - "source /data/scripts/deploy_v2.sh dev sudoryclient"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
    - if: $CI_COMMIT_BRANCH =~ /\b^(issue|feature|bugfix|improvement).*$\b/
      when: manual
  allow_failure: true
