FROM alpine:latest  as common-build-stage
LABEL version=0.1.0

RUN apk update && apk add --no-cache openssh-client bash dbus

COPY ./bin/client/sudory-client /
COPY ./conf/script/client/entrypoint.sh /

ENV S_SERVER_URL ""
ENV S_CLUSTER_ID ""
ENV S_TOKEN ""

ENTRYPOINT ["sh", "/entrypoint.sh"]