FROM alpine:latest
LABEL version=0.1.0

RUN apk update && apk add --no-cache openssh-client bash dbus

COPY ./bin/client/sudory-client /
COPY ./conf/client/entrypoint.sh /

ENV S_SERVER_URL ""
ENV S_CLUSTER_ID ""

ENTRYPOINT ["sh", "/entrypoint.sh"]