FROM alpine:3.13.2
LABEL version=0.1.0

RUN apk update && apk add --no-cache openssh-client bash 

COPY ./bin/client/sudory-client /
COPY ./conf/client/entrypoint.sh /

ENV S_SERVER_URL ""
ENV S_CLUSTER_ID ""

ENTRYPOINT ./entrypoint.sh