apiVersion: v1
kind: Namespace
metadata:
  name: sudory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  namespace: sudory
data:
  SUDORY_DB_HOST: "ncdb-mariadb-primary.mariadb.svc.cluster.local"
  SUDORY_DB_PORT: "3306"
  SUDORY_DB_SCHEME: "nc_sudory"
  SUDORY_DB_EXPORT_PATH: "."
  SUDORY_DB_ROOT_USERNAME: "root"
  SUDORY_DB_SERVER_USERNAME: "user"
  SUDORY_LOG_SEVERITY: "info"
  SUDORY_LOG_SYSTEM_EVENT: "false"
  SUDORY_LOG_VERBOSE: "true"
  SUDORY_LOG_VERBOSELEVEL: "9"
  SUDORY_LOG_FILENAME: "./sudory.log"
  SUDORY_LOG_MAXSIZE: "10"
  SUDORY_LOG_MAXAGE: "5"
  SUDORY_LOG_MAXBACKUPS: "10"
  SUDORY_LOG_COMPRESS: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-rules-configmap
  labels:
    sudory: server
data:
  events.yml: |
    events:
    - event:
      name: 'service-poll-in'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'event'
    - event:
      name: 'service-poll-out'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'event'
    - event:
      name: 'client-auth-accept'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'client'   
    - event:
      name: 'nc_metric'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'nc_metric'
    - event:
      name: 'nc_metric_received'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'nc_metric_received'
    - event:
      name: 'nc_resource'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'nc_resource'
    - event:
      name: 'nc_alert'
      update-interval: 5s
      notifiers:
      - notifier:
        type: console
      - notifier:
        type: 'rabbitmq'
        url: 'amqp://nexclipper:nexclipper@ncmq-rabbitmq.rabbitmq.svc.cluster.local:5672/nexclipper'
        exchange: ''
        routing-key: 'nc_alert'
  enigma.yml: |
    enigma:
      sudory.default.crypto:
        block-method: none
        block-size: 0
        block-key: 
        cipher-mode: none
        cipher-salt: null
        padding: none
        strconv: plain

---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  namespace: sudory
spec:
  type: LoadBalancer
  ports:
    - port: 8099
      targetPort: 8099
  selector:
    sudory: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
  namespace: sudory
spec:
  selector:
    matchLabels:
      sudory: server
  replicas: 1
  template:
    metadata:
      labels:
        sudory: server
    spec:
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          ports:
            - containerPort: 8099
          resources: {}
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
          env:
            - name: SUDORY_DB_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ncdb-mariadb
                  key: mariadb-password
            - name: SUDORY_DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ncdb-mariadb
                  key: mariadb-root-password
          livenessProbe:
            tcpSocket:
              port: 8099
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - mountPath: /app/conf/rules
              name: server-rules-configmap
      volumes:
        - configMap:
            defaultMode: 420
            name: ${APP_IMAGE_NAME}-rules-configmap
          name: server-rules-configmap
