apiVersion: v1
kind: Namespace
metadata:
  name: sudoryclient
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  namespace: sudoryclient
  labels:
    sudory: client
data:
  S_SERVER_URL: '$S_SERVER_URL'
  S_CLUSTER_ID: '$S_CLUSTER_ID'
  S_TOKEN: '$S_TOKEN'


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
  namespace: sudoryclient
  labels:
    sudory: client
spec:
  selector:
    matchLabels:
      sudory: client
  replicas: 1
  template:
    metadata:
      labels:
        sudory: client
    spec:
      serviceAccountName: sudory-controller
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          resources: {}
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: sudory-controller
  namespace: sudoryclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sudory-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - "monitoring.coreos.com"
  resources:
  - prometheuses
  - prometheusrules
  - servicemonitors
  verbs:
  - get
  - list
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sudory-controller
subjects:
- kind: ServiceAccount
  name: sudory-controller
  namespace: sudoryclient
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sudory-controller
