apiVersion: v1
kind: Namespace
metadata:
  name: sudoryclient
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: $APP_IMAGE_NAME-configmap
  namespace: sudoryclient
  labels:
    sudory: client
data:
  S_SERVER_URL: '$S_SERVER_URL'
  S_CLUSTER_ID: '$S_CLUSTER_ID'
  S_TOKEN: '$S_TOKEN'


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_IMAGE_NAME
  namespace: sudoryclient
  labels:
    sudory: client
spec:
  selector:
    matchLabels:
      sudory: client
  replicas: 1
  template:
    metadata:
      labels:
        sudory: client
    spec:
      containers:
        - name: $APP_IMAGE_NAME
          image: ${IMG_TAG_TO_DEPLOY}
          resources: {}
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
