---
{{if .Values.client.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sudory-client-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    sudory: client
data:
{{ toYaml .Values.client.environment_variable.data | indent 2  }}
{{- end}}
---
{{if .Values.server.serverrule.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sudory-server-rules-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
    sudory: server
data:
{{ toYaml .Values.server.serverrule.data | indent 2 }}
{{- end}}
---

{{if .Values.server.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sudory-server-configmap
  namespace: {{ .Release.Namespace }}
data:
{{ toYaml .Values.server.environment_variable.data | indent 2  }}
{{- end}}
---
