use sudory;

-- services for test
-- -- k8s
-- ---- v1
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (1, '1', 'service-pods-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (2, '2', 'service-pods-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (3, '3', 'service-namespaces-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (4, '4', 'service-namespaces-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (5, '5', 'service-configmaps-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (6, '6', 'service-configmaps-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (7, '7', 'service-events-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (8, '8', 'service-events-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (9, '9', 'service-nodes-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (10, '10', 'service-nodes-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (11, '11', 'service-persistentvolumes-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (12, '12', 'service-persistentvolumes-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (13, '13', 'service-secrets-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (14, '14', 'service-secrets-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (15, '15', 'service-endpoints-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (16, '16', 'service-endpoints-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (17, '17', 'service-persistentvolumeclaims-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (18, '18', 'service-persistentvolumeclaims-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (19, '19', 'service-services-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (20, '20', 'service-services-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- ---- apps/v1
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (51, '51', 'service-deployments-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (52, '52', 'service-deployments-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (53, '53', 'service-statefulsets-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (54, '54', 'service-statefulsets-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (55, '55', 'service-daemonsets-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (56, '56', 'service-daemonsets-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (57, '57', 'service-replicasets-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (58, '58', 'service-replicasets-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- ---- networking.k8s.io/v1
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (81, '81', 'service-ingresses-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (82, '82', 'service-ingresses-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- ---- storage.k8s.io/v1
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (91, '91', 'service-storageclasses-get-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (92, '92', 'service-storageclasses-list-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- -- p8s
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (201, '201', 'service-p8s-query-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (202, '202', 'service-p8s-query_range-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (203, '203', 'service-p8s-alerts-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (204, '204', 'service-p8s-rules-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- -- jq
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (301, '301', 'service-jq-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- -- helm
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (401, '401', 'service-helm-install-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (402, '402', 'service-helm-uninstall-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `service` (`id`, `uuid`, `name`, `summary`, `api_version`, `template_uuid`, `origin_kind`, `origin_uuid`, `cluster_uuid`, `assigned_client_uuid`, `step_count`, `step_position`, `type`, `epoch`, `interval`, `status`, `result`, `created`, `updated`, `deleted`) VALUES (403, '403', 'service-helm-upgrade-1', NULL, 'v1', 'template_uuid', 'template', 'template_uuid', '00000000000000000000000000000003', NULL, 0, 0, 0, 0, 0, 1, NULL, NULL, NULL, NULL);

-- service_steps for test
-- -- k8s
-- ---- v1
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (1, '1', 'step-pods-get-1', NULL, 'v1', '1', 0, 'kubernetes.pods.get.v1', '{"namespace":"prom","name":"prometheus-ppp-kube-prometheus-stack-prometheus-0"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (2, '2', 'step-pods-list-1', NULL, 'v1', '2', 0, 'kubernetes.pods.list.v1', '{"release":"prometheus"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (3, '3', 'step-namespaces-get-1', NULL, 'v1', '3', 0, 'kubernetes.namespaces.get.v1', '{"name":"prom"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (4, '4', 'step-namespaces-list-1', NULL, 'v1', '4', 0, 'kubernetes.namespaces.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (5, '5', 'step-configmaps-get-1', NULL, 'v1', '5', 0, 'kubernetes.configmaps.get.v1', '{"namespace":"prom","name":"ppp-kube-prometheus-stack-kubelet"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (6, '6', 'step-configmaps-list-1', NULL, 'v1', '6', 0, 'kubernetes.configmaps.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (7, '7', 'step-events-get-1', NULL, 'v1', '7', 0, 'kubernetes.events.get.v1', '{"namespace":"prom","name":"event1"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (8, '8', 'step-events-list-1', NULL, 'v1', '8', 0, 'kubernetes.events.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (9, '9', 'step-nodes-get-1', NULL, 'v1', '9', 0, 'kubernetes.nodes.get.v1', '{"name":"wslkindmultinodes-control-plane"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (10, '10', 'step-nodes-list-1', NULL, 'v1', '10', 0, 'kubernetes.nodes.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (11, '11', 'step-persistentvolumes-get-1', NULL, 'v1', '11', 0, 'kubernetes.persistentvolumes.get.v1', '{"namespace":"prom","name":"pvc-8d250848-31d2-47f1-ba1e-133a0e73d030"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (12, '12', 'step-persistentvolumes-list-1', NULL, 'v1', '12', 0, 'kubernetes.persistentvolumes.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (13, '13', 'step-secrets-get-1', NULL, 'v1', '13', 0, 'kubernetes.secrets.get.v1', '{"namespace":"prom","name":"ppp-grafana"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (14, '14', 'step-secrets-list-1', NULL, 'v1', '14', 0, 'kubernetes.secrets.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (15, '15', 'step-endpoints-get-1', NULL, 'v1', '15', 0, 'kubernetes.endpoints.get.v1', '{"namespace":"prom","name":"ppp-kube-prometheus-stack-prometheus"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (16, '16', 'step-endpoints-list-1', NULL, 'v1', '16', 0, 'kubernetes.endpoints.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (17, '17', 'step-persistentvolumeclaims-get-1', NULL, 'v1', '17', 0, 'kubernetes.persistentvolumeclaims.get.v1', '{"namespace":"default","name":"data-mysql-1644406894-0"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (18, '18', 'step-persistentvolumeclaims-list-1', NULL, 'v1', '18', 0, 'kubernetes.persistentvolumeclaims.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (19, '19', 'step-services-get-1', NULL, 'v1', '19', 0, 'kubernetes.services.get.v1', '{"namespace":"prom","name":"ppp-grafana"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (20, '20', 'step-services-list-1', NULL, 'v1', '20', 0, 'kubernetes.services.list.v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- ---- apps/v1
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (51, '51', 'step-deployments-get-1', NULL, 'v1', '51', 0, 'kubernetes.deployments.get.apps/v1', '{"namespace":"prom","name":"ppp-grafana"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (52, '52', 'step-deployments-list-1', NULL, 'v1', '52', 0, 'kubernetes.deployments.list.apps/v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (53, '53', 'step-statefulsets-get-1', NULL, 'v1', '53', 0, 'kubernetes.statefulsets.get.apps/v1', '{"namespace":"prom","name":"prometheus-ppp-kube-prometheus-stack-prometheus"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (54, '54', 'step-statefulsets-list-1', NULL, 'v1', '54', 0, 'kubernetes.statefulsets.list.apps/v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (55, '55', 'step-daemonsets-get-1', NULL, 'v1', '55', 0, 'kubernetes.daemonsets.get.apps/v1', '{"namespace":"prom","name":"ppp-prometheus-node-exporter"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (56, '56', 'step-daemonsets-list-1', NULL, 'v1', '56', 0, 'kubernetes.daemonsets.list.apps/v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (57, '57', 'step-replicasets-get-1', NULL, 'v1', '57', 0, 'kubernetes.replicasets.get.apps/v1', '{"namespace":"prom","name":"ppp-grafana-5497c74fdc"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (58, '58', 'step-replicasets-list-1', NULL, 'v1', '58', 0, 'kubernetes.replicasets.list.apps/v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- ---- networking.k8s.io/v1
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (81, '81', 'step-ingresses-get-1', NULL, 'v1', '81', 0, 'kubernetes.ingresses.get.networking.k8s.io/v1', '{"namespace":"prom","name":"ingress1"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (82, '82', 'step-ingresses-list-1', NULL, 'v1', '82', 0, 'kubernetes.ingresses.list.networking.k8s.io/v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- ---- storage.k8s.io/v1
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (91, '91', 'step-storageclasses-get-1', NULL, 'v1', '91', 0, 'kubernetes.storageclasses.get.storage.k8s.io/v1', '{"name":"standard"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (92, '92', 'step-storageclasses-list-1', NULL, 'v1', '92', 0, 'kubernetes.storageclasses.list.storage.k8s.io/v1', '{}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- -- p8s
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (201, '201', 'step-p8s-query-1', NULL, 'v1', '201', 0, 'prometheus.query.v1', '{"url":"http://localhost:9090","query":"up","time":"2022-02-17T01:59:51.781Z"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (202, '202', 'step-p8s-query_range-1', NULL, 'v1', '202', 0, 'prometheus.query_range.v1', '{"url":"http://localhost:9090","end":"2022-02-17T02:10:30.781Z","query":"rate(prometheus_tsdb_head_samples_appended_total[5m])","start":"2022-02-17T01:10:30.781Z","step":"1y"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (203, '203', 'step-p8s-alerts-1', NULL, 'v1', '203', 0, 'prometheus.alerts.v1', '{"url":"http://localhost:9090"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (204, '204', 'step-p8s-rules-1', NULL, 'v1', '204', 0, 'prometheus.rules.v1', '{"url":"http://localhost:9090"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- -- jq
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (301, '301', 'step-jq-1', NULL, 'v1', '301', 0, 'jq', '{"filter":".metadata.name","input":{"metadata":{"name":"prom","uid":"27ad4ebf-360e-4a2f-9540-7049b2755886","resourceVersion":"486439","creationTimestamp":"2022-02-14T04:40:26Z","labels":{"kubernetes.io/metadata.name":"prom"},"managedFields":[{"manager":"kubectl-create","operation":"Update","apiVersion":"v1","time":"2022-02-14T04:40:26Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:kubernetes.io/metadata.name":{}}}}}]},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Active"}}}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);

-- -- helm
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (401, '401', 'step-helm-install-1', NULL, 'v1', '401', 0, 'helm.install', '{"name":"ppp","chart_name":"kube-prometheus-stack","chart_version":"31.0.0","namespace":"prom","repo_url":"https://prometheus-community.github.io/helm-charts","values":{"key1":"val1","key2":"val2"}}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (402, '402', 'step-helm-uninstall-1', NULL, 'v1', '402', 0, 'helm.uninstall', '{"name":"ppp","namespace":"prom"}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
INSERT INTO `service_step` (`id`, `uuid`, `name`, `summary`, `api_version`, `service_uuid`, `sequence`, `method`, `args`, `result_filter`, `status`, `result`, `started`, `ended`, `created`, `updated`, `deleted`) VALUES (403, '403', 'step-helm-upgrade-1', NULL, 'v1', '403', 0, 'helm.upgrade', '{"name":"ppp","chart_name":"kube-prometheus-stack","chart_version":"33.2.0","namespace":"prom","repo_url":"https://prometheus-community.github.io/helm-charts","values":{"key3":"val3","key4":"val4"}}', NULL, 1, '', NULL, NULL, NULL, NULL, NULL);
