// Code generated by Ice-cream-maker DO NOT EDIT.
package v2
 
func (GlobalVariables) ColumnNames() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"value",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (GlobalVariables) ColumnNamesWithAlias() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"value",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (row GlobalVariables) Values() []interface{} {
	return []interface{}{
		row.ID,
		row.Uuid,
		row.Name,
		row.Summary,
		row.Value,
		row.Created,
		row.Updated,
		row.Deleted,
	}
}

type Scanner interface {
	Scan(dest ...interface{}) error
}
 
func (row *GlobalVariables) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.ID,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.Value,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	)
}
 
func (row *GlobalVariables) Ptrs() []interface{} {
	return []interface{}{
		&row.ID,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.Value,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	}
}
