apiVersion: v1
kind: Namespace
metadata:
  name: sudory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-configmap
  namespace: sudory
data:
  SUDORY_DB_HOST: "ncdb-mariadb-primary.mariadb.svc.cluster.local"
  SUDORY_DB_PORT: "3306"
  SUDORY_DB_SCHEME: "nc_sudory"
  SUDORY_DB_EXPORT_PATH: "."
  SUDORY_DB_SERVER_USERNAME: "user"
  SUDORY_LOG_SEVERITY: "info"
  SUDORY_LOG_SYSTEM_EVENT: "false"
  SUDORY_LOG_VERBOSE: "true"
  SUDORY_LOG_VERBOSELEVEL: "9"
  SUDORY_LOG_FILENAME: "./sudory.log"
  SUDORY_LOG_MAXSIZE: "10"
  SUDORY_LOG_MAXAGE: "5"
  SUDORY_LOG_MAXBACKUPS: "10"
  SUDORY_LOG_COMPRESS: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_IMAGE_NAME}-rules-configmap
  labels:
    sudory: server
data:
  enigma.yml: |
    enigma:
      sudory.default.crypto:
        block-method: none
        block-size: 0
        block-key: 
        cipher-mode: none
        cipher-salt: null
        padding: none
        strconv: plain

---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_IMAGE_NAME}
  namespace: sudory
spec:
  type: LoadBalancer
  ports:
    - port: 8099
      targetPort: 8099
  selector:
    sudory: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_IMAGE_NAME}
  namespace: sudory
spec:
  selector:
    matchLabels:
      sudory: server
  replicas: 1
  template:
    metadata:
      labels:
        sudory: server
    spec:
      containers:
        - name: ${APP_IMAGE_NAME}
          image: ${IMG_TAG_TO_DEPLOY}
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
          securityContext:
            runAsNonRoot: true
            runAsUser: 1002
            capabilities:
              drop:
                - SETUID
                - SETGID
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 1500m
              memory: 1024Mi
          envFrom:
            - configMapRef:
                name: ${APP_IMAGE_NAME}-configmap
          env:
            - name: SUDORY_DB_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ncdb-mariadb
                  key: mariadb-password
          livenessProbe:
            tcpSocket:
              port: 8099
            initialDelaySeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - mountPath: /app/conf/rules
              name: server-rules-configmap
      volumes:
        - configMap:
            defaultMode: 420
            name: ${APP_IMAGE_NAME}-rules-configmap
          name: server-rules-configmap
