INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('20000000000000000000000000000004', 'helm_get_values', 'class=\'helm\' resource=\'get_values\' verb=\'\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('20000000000000000000000000000004', 'helm_get_values_0', 'class=\'helm\' resource=\'get_values\' verb=\'\' group_version=\'\'', '20000000000000000000000000000004', '0', 'helm.get_values', '{"type":"object","properties":{"namespace":{"type":"string","pattern":"^."},"name":{"type":"string","pattern":"^."},"all":{"type":"boolean"}},"required":["namespace","name"]}', NULL, NOW());

INSERT INTO `template_recipe` (`id`, `method`, `args`, `name`, `summary`, `created`) VALUES (126, 'helm.get_values', '{"type":"object","properties":{"namespace":{"type":"string","pattern":"^."},"name":{"type":"string","pattern":"^."},"all":{"type":"boolean"}},"required":["namespace","name"]}', 'helm-get_values', 'namespace:require;string;,name:require;string;,all:optional;boolean;', NOW());

UPDATE `template_command` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"required":["name","chart_name","repo_url","namespace"]}' WHERE uuid='20000000000000000000000000000001';
UPDATE `template_command` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"required":["name","chart_name","repo_url","namespace"]}' WHERE uuid='20000000000000000000000000000003';

UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"required":["name","chart_name","repo_url","namespace"]}' WHERE id=118;
UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"required":["name","chart_name","repo_url","namespace"]}' WHERE id=120;
