UPDATE `template_command` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"id":{"type":"string","pattern":"^."}},"required":["credential_key","id"]}' WHERE uuid='50000000000000000000000000000003';
UPDATE `template_command` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"query":{"type":"object","additionalProperties":{"type":"string"}}},"required":["credential_key"]}' WHERE uuid='50000000000000000000000000000004';
UPDATE `template_command` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"id":{"type":"string","pattern":"^."}},"required":["credential_key","id"]}' WHERE uuid='50000000000000000000000000000011';
UPDATE `template_command` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"query":{"type":"object","additionalProperties":{"type":"string"}}},"required":["credential_key"]}' WHERE uuid='50000000000000000000000000000012';

UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"id":{"type":"string","pattern":"^."}},"required":["credential_key","id"]}' WHERE method='openstack.compute.servers.get';
UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"query":{"type":"object","additionalProperties":{"type":"string"}}},"required":["credential_key"]}' WHERE method='openstack.compute.servers.list';
UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"id":{"type":"string","pattern":"^."}},"required":["credential_key","id"]}' WHERE method='openstack.compute.hypervisors.get';
UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"credential_key":{"type":"string","pattern":"^."},"query":{"type":"object","additionalProperties":{"type":"string"}}},"required":["credential_key"]}' WHERE method='openstack.compute.hypervisors.list';
