INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('40000000000000000000000000000001', 'grafana_datasources_get', 'class=\'grafana\' resource=\'datasources\' verb=\'get\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('40000000000000000000000000000001', 'grafana_datasources_get_0', 'class=\'grafana\' resource=\'datasources\' verb=\'get\' group_version=\'\'', '40000000000000000000000000000001', '0', 'grafana.datasources.get', '{"type":"object","properties":{"url":{"type":"string","pattern":"^."},"credential_key":{"type":"string","pattern":"^."},"datasource_id":{"type":"string","pattern":"^."},"datasource_uid":{"type":"string","pattern":"^."},"datasource_name":{"type":"string","pattern":"^."}},"required":["url","credential_key"],"oneOf":[{"required":["datasource_id"]},{"required":["datasource_uid"]},{"required":["datasource_name"]}]}', NULL, NOW());
INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('40000000000000000000000000000002', 'grafana_datasources_list', 'class=\'grafana\' resource=\'datasources\' verb=\'list\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('40000000000000000000000000000002', 'grafana_datasources_list_0', 'class=\'grafana\' resource=\'datasources\' verb=\'list\' group_version=\'\'', '40000000000000000000000000000002', '0', 'grafana.datasources.list', '{"type":"object","properties":{"url":{"type":"string","pattern":"^."},"credential_key":{"type":"string","pattern":"^."}},"required":["url","credential_key"]}', NULL, NOW());
INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('40000000000000000000000000000003', 'grafana_datasources_delete', 'class=\'grafana\' resource=\'datasources\' verb=\'delete\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('40000000000000000000000000000003', 'grafana_datasources_delete_0', 'class=\'grafana\' resource=\'datasources\' verb=\'delete\' group_version=\'\'', '40000000000000000000000000000003', '0', 'grafana.datasources.delete', '{"type":"object","properties":{"url":{"type":"string","pattern":"^."},"credential_key":{"type":"string","pattern":"^."},"datasource_id":{"type":"string","pattern":"^."},"datasource_uid":{"type":"string","pattern":"^."},"datasource_name":{"type":"string","pattern":"^."}},"required":["url","credential_key"],"oneOf":[{"required":["datasource_id"]},{"required":["datasource_uid"]},{"required":["datasource_name"]}]}', NULL, NOW());

INSERT INTO `template_recipe` ( `method`, `args`, `name`, `summary`, `created`) VALUES ('grafana.datasources.get', '{"type":"object","properties":{"url":{"type":"string","pattern":"^."},"credential_key":{"type":"string","pattern":"^."},"datasource_id":{"type":"string","pattern":"^."},"datasource_uid":{"type":"string","pattern":"^."},"datasource_name":{"type":"string","pattern":"^."}},"required":["url","credential_key"],"oneOf":[{"required":["datasource_id"]},{"required":["datasource_uid"]},{"required":["datasource_name"]}]}', 'grafana-datasources-get', 'url:required;string;,credential_key:required;string;', NOW());
INSERT INTO `template_recipe` ( `method`, `args`, `name`, `summary`, `created`) VALUES ('grafana.datasources.list', '{"type":"object","properties":{"url":{"type":"string","pattern":"^."},"credential_key":{"type":"string","pattern":"^."}},"required":["url","credential_key"]}', 'grafana-datasources-list', 'url:required;string;,credential_key:required;string;', NOW());
INSERT INTO `template_recipe` ( `method`, `args`, `name`, `summary`, `created`) VALUES ('grafana.datasources.delete', '{"type":"object","properties":{"url":{"type":"string","pattern":"^."},"credential_key":{"type":"string","pattern":"^."},"datasource_id":{"type":"string","pattern":"^."},"datasource_uid":{"type":"string","pattern":"^."},"datasource_name":{"type":"string","pattern":"^."}},"required":["url","credential_key"],"oneOf":[{"required":["datasource_id"]},{"required":["datasource_uid"]},{"required":["datasource_name"]}]}', 'grafana-datasources-delete', 'url:required;string;,credential_key:required;string;', NOW());
