INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('20000000000000000000000000000005', 'helm_repo_add', 'class=\'helm\' resource=\'repo_add\' verb=\'\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('20000000000000000000000000000005', 'helm_repo_add_0', 'class=\'helm\' resource=\'repo_add\' verb=\'\' group_version=\'\'', '20000000000000000000000000000005', '0', 'helm.repo_add', '{"type":"object","properties":{"repo_url":{"type":"string","pattern":"^."},"repo_name":{"type":"string","pattern":"^."}},"required":["repo_url","repo_name"]}', NULL, NOW());
INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('20000000000000000000000000000006', 'helm_repo_list', 'class=\'helm\' resource=\'repo_list\' verb=\'\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('20000000000000000000000000000006', 'helm_repo_list_0', 'class=\'helm\' resource=\'repo_list\' verb=\'\' group_version=\'\'', '20000000000000000000000000000006', '0', 'helm.repo_list', '{}', NULL, NOW());
INSERT INTO `template` (`uuid`, `name`, `summary`, `origin`, `created`) VALUES ('20000000000000000000000000000007', 'helm_repo_update', 'class=\'helm\' resource=\'repo_update\' verb=\'\' group_version=\'\'', 'predefined', NOW());
INSERT INTO `template_command` (`uuid`, `name`, `summary`, `template_uuid`, `sequence`, `method`, `args`, `result_filter`, `created`) VALUES ('20000000000000000000000000000007', 'helm_repo_update_0', 'class=\'helm\' resource=\'repo_update\' verb=\'\' group_version=\'\'', '20000000000000000000000000000007', '0', 'helm.repo_update', '{"type":"object","properties":{"repo_name":{"type":"string","pattern":"^."}},"required":["repo_name"]}', NULL, NOW());

INSERT INTO `template_recipe` (`id`, `method`, `args`, `name`, `summary`, `created`) VALUES (127, 'helm.repo_add', '{"type":"object","properties":{"repo_url":{"type":"string","pattern":"^."},"repo_name":{"type":"string","pattern":"^."}},"required":["repo_url","repo_name"]}', 'helm-repo_add', 'repo_url:require;string;,repo_name:require;string;', NOW());
INSERT INTO `template_recipe` (`id`, `method`, `args`, `name`, `summary`, `created`) VALUES (128, 'helm.repo_list', '{}', 'helm-repo_list', '', NOW());
INSERT INTO `template_recipe` (`id`, `method`, `args`, `name`, `summary`, `created`) VALUES (129, 'helm.repo_update', '{"type":"object","properties":{"repo_name":{"type":"string","pattern":"^."}},"required":["repo_name"]}', 'helm-repo_update', 'repo_name:require;string;', NOW());

UPDATE `template_command` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"repo_name":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"oneOf":[{"required":["name","chart_name","repo_url","namespace"]},{"required":["name","chart_name","repo_name","namespace"]}]}' WHERE uuid='20000000000000000000000000000001';
UPDATE `template_command` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"repo_name":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"oneOf":[{"required":["name","chart_name","repo_url","namespace"]},{"required":["name","chart_name","repo_name","namespace"]}]}' WHERE uuid='20000000000000000000000000000003';

UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"repo_name":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"oneOf":[{"required":["name","chart_name","repo_url","namespace"]},{"required":["name","chart_name","repo_name","namespace"]}]}' WHERE id=118;
UPDATE `template_recipe` SET `args`='{"type":"object","properties":{"name":{"type":"string","pattern":"^."},"chart_name":{"type":"string","pattern":"^."},"repo_url":{"type":"string","pattern":"^."},"repo_name":{"type":"string","pattern":"^."},"namespace":{"type":"string","pattern":"^."},"chart_version":{"type":"string"},"values":{"type":"object"}},"oneOf":[{"required":["name","chart_name","repo_url","namespace"]},{"required":["name","chart_name","repo_name","namespace"]}]}' WHERE id=120;
