apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudory-client
  namespace: sudoryclient
spec:
  selector:
    matchLabels:
      sudory:  client
  replicas: 1 
  template:
    metadata:
      labels:
        sudory: client
    spec:
      serviceAccountName: sudory-controller
      containers:
        - name: sudory-client
          image: repo.nexclipper.io/nexclipper/sudory-client:0.2.1
          env:
            - name: S_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: sudory-configmap
                  key: server
            - name: S_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: sudory-configmap
                  key: clusterid
            - name: S_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: sudory-configmap
                  key: token
