apiVersion: v1
kind: Namespace
metadata:
  name: sudory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sudory-configmap
  namespace: sudory
data:
  server: "'192.168.10.0:8099'"
  clusterid: "1"
