apiVersion: v1
kind: ServiceAccount
metadata: 
  name: sudory-controller
  namespace: sudoryclient
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sudory-controller
  namespace: sudoryclient 
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - nodes
  - persistentvolumes
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups: ["*"]
  resources: ["*"]
  verbs:
  - get
  - list
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sudory-controller
subjects:
- kind: ServiceAccount
  name: sudory-controller
  namespace: sudoryclient 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sudory-controller
