// Code generated by Ice-cream-maker DO NOT EDIT.
package v2
 
func (ClusterInformation) ColumnNames() []string {
	return []string{
 		"id",
 		"cluster_uuid",
 		"polling_count",
 		"polling_offset",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (row ClusterInformation) Values() []interface{} {
	return []interface{}{
		row.ID,
		row.ClusterUuid,
		row.PollingCount,
		row.PollingOffset,
		row.Created,
		row.Updated,
		row.Deleted,
	}
}

type Scanner interface {
	Scan(dest ...interface{}) error
}
 
func (row *ClusterInformation) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.ID,
		&row.ClusterUuid,
		&row.PollingCount,
		&row.PollingOffset,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	)
}
 
func (row *ClusterInformation) Ptrs() []interface{} {
	return []interface{}{
		&row.ID,
		&row.ClusterUuid,
		&row.PollingCount,
		&row.PollingOffset,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	}
}
