apiVersion: v1
kind: Namespace
metadata:
  name: sudory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sudory-configmap
  namespace: sudory
data:
  db_host: ""
  db_port: "3306"
  db_scheme: "sudory"
  db_export_path: "."
  db_root_username: "root"
  db_server_username: "sudory"
  log_severity: "info"
  log_system_event: "false"
  log_verbose: "true"
  log_verboselevel: "9"
  log_filename: "./sudory.log"
  log_maxsize: "10"
  log_maxage: "5"
  log_maxbackups: "10"
  log_compress: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: sudory-secret
  namespace: sudory
type: Opaque
data:
  db_root_password: ""
  db_server_password: ""
