// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://nexclipper.io",
            "email": "jaehoon@nexclipper.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/client/auth": {
            "post": {
                "description": "Auth a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client/auth"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client 의 Uuid",
                        "name": "client_uuid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cluster 의 Uuid",
                        "name": "cluster_uuid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspClient"
                        }
                    }
                }
            }
        },
        "/client/service": {
            "put": {
                "description": "Poll a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client 의 ClusterUuid",
                        "name": "cluster_uuid",
                        "in": "query"
                    },
                    {
                        "description": "HttpReqClientSideService",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpReqClientSideService"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspClientSideService"
                            }
                        }
                    }
                }
            }
        },
        "/server/client": {
            "get": {
                "description": "Find client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/client"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client 의 Uuid",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Client 의 Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Client 의 ClusterUuid",
                        "name": "cluster_uuid",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspClient"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/client"
                ],
                "parameters": [
                    {
                        "description": "HttpReqClient",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqClient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/client/{uuid}": {
            "get": {
                "description": "Get a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/client"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspClient"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/client"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqClient",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqClient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/client"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/cluster": {
            "get": {
                "description": "Find cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster 의 Uuid",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cluster 의 Name",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspCluster"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/cluster"
                ],
                "parameters": [
                    {
                        "description": "HttpReqCluster",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqCluster"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/cluster/{uuid}": {
            "get": {
                "description": "Get a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspCluster"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqCluster",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqCluster"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete a cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/service": {
            "get": {
                "description": "Find []Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service 의 ClusterUuid",
                        "name": "cluster_uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Service 의 Uuid",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Service 의 Status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspService"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service"
                ],
                "parameters": [
                    {
                        "description": "HttpReqServiceCreate",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqServiceCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/service/{service_uuid}/step": {
            "get": {
                "description": "Get a Service Step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service_step"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceStep 의 service_uuid",
                        "name": "service_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspServiceStep"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Service Step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service_step"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceStep 의 service_uuid",
                        "name": "service_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqServiceStep",
                        "name": "step",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqServiceStep"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/service/{service_uuid}/step/{uuid}": {
            "get": {
                "description": "Get a Service Step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service_step"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceStep 의 service_uuid",
                        "name": "service_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ServiceStep 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspServiceStep"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a Service Step",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service_step"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceStep 의 service_uuid",
                        "name": "service_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ServiceStep 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqServiceStep",
                        "name": "step",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqServiceStep"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service_step"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceStep 의 service_uuid",
                        "name": "service_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ServiceStep 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/service/{uuid}": {
            "get": {
                "description": "Get a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspService"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqService",
                        "name": "service",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqService"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete a Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/service"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/template": {
            "get": {
                "description": "Find []template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template 의 Uuid",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Template 의 Name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Template 의 Origin",
                        "name": "origin",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template"
                ],
                "parameters": [
                    {
                        "description": "HttpReqTemplateCreate",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqTemplateCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/template/{template_uuid}/command": {
            "get": {
                "description": "Get template commands",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template_command"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "HttpReqTemplate 의 Uuid",
                        "name": "template_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.HttpRspTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a template command",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template_command"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "HttpReqTemplate 의 Uuid",
                        "name": "template_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqTemplateCommand",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqTemplateCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/template/{template_uuid}/command/{uuid}": {
            "get": {
                "description": "Get a template command",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template_command"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "HttpReqTemplate 의 Uuid",
                        "name": "template_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "HttpReqTemplateCommand 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspTemplate"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a template command",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template_command"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "HttpReqTemplateCommand 의 TemplateUuid",
                        "name": "template_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "HttpReqTemplateCommand 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "HttpReqTemplateCommand",
                        "name": "command",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqTemplateCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete a template command",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template_command"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "HttpReqTemplate 의 Uuid",
                        "name": "template_uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "HttpReqTemplateCommand 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/server/template/{uuid}": {
            "get": {
                "description": "Get a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.HttpRspTemplate"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template 의 Uuid",
                        "name": "uuid",
                        "in": "path"
                    },
                    {
                        "description": "HttpReqTemplate",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.HttpReqTemplate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            },
            "delete": {
                "description": "Delete a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server/template"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template 의 Uuid",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.HttpReqClient": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "ClusterUuid",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqClientSideService": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "클러스터 UUID",
                    "type": "string"
                },
                "epoch": {
                    "description": "Epoch -1: infinite, 0 :",
                    "type": "integer"
                },
                "interval": {
                    "description": "Interval",
                    "type": "integer"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "type": "integer"
                },
                "step_count": {
                    "description": "스탭 카운트",
                    "type": "integer"
                },
                "step_position": {
                    "description": "스탭 Position",
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ServiceStep"
                    }
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "type": {
                    "description": "Type; 0: Once, 1: repeat(epoch, interval)",
                    "type": "integer"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqCluster": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqService": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "클러스터 UUID",
                    "type": "string"
                },
                "epoch": {
                    "description": "Epoch -1: infinite, 0 :",
                    "type": "integer"
                },
                "interval": {
                    "description": "Interval",
                    "type": "integer"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "type": "integer"
                },
                "step_count": {
                    "description": "스탭 카운트",
                    "type": "integer"
                },
                "step_position": {
                    "description": "스탭 Position",
                    "type": "integer"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "type": {
                    "description": "Type; 0: Once, 1: repeat(epoch, interval)",
                    "type": "integer"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqServiceCreate": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "클러스터 UUID",
                    "type": "string"
                },
                "epoch": {
                    "description": "Epoch -1: infinite, 0 :",
                    "type": "integer"
                },
                "interval": {
                    "description": "Interval",
                    "type": "integer"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "type": "integer"
                },
                "step_count": {
                    "description": "스탭 카운트",
                    "type": "integer"
                },
                "step_position": {
                    "description": "스탭 Position",
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ServiceStep"
                    }
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "type": {
                    "description": "Type; 0: Once, 1: repeat(epoch, interval)",
                    "type": "integer"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqServiceStep": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "args": {
                    "description": "arguments",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ended": {
                    "description": "Started 스탭 완료 시간",
                    "type": "string"
                },
                "method": {
                    "description": "메소드",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "sequence": {
                    "description": "순서",
                    "type": "integer"
                },
                "service_uuid": {
                    "description": "서비스 Uuid",
                    "type": "string"
                },
                "srated": {
                    "description": "Started 스탭 시작 시간",
                    "type": "string"
                },
                "status": {
                    "description": "Status 상태",
                    "type": "integer"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqTemplate": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "origin": {
                    "description": "origin\n@example: predefined, userdefined",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqTemplateCommand": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "args": {
                    "description": "arguments",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "description": "메소드\n@example: \"kubernetes.deployment.get.v1\", \"kubernetes.pod.list.v1\"",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "sequence": {
                    "description": "순서",
                    "type": "integer"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "template_uuid": {
                    "description": "템플릿 UUID",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpReqTemplateCreate": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "commands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.TemplateCommand"
                    }
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "origin": {
                    "description": "origin\n@example: predefined, userdefined",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpRspClient": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "ClusterUuid",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpRspClientSideService": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "클러스터 UUID",
                    "type": "string"
                },
                "epoch": {
                    "description": "Epoch -1: infinite, 0 :",
                    "type": "integer"
                },
                "interval": {
                    "description": "Interval",
                    "type": "integer"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "type": "integer"
                },
                "step_count": {
                    "description": "스탭 카운트",
                    "type": "integer"
                },
                "step_position": {
                    "description": "스탭 Position",
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ServiceStep"
                    }
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "type": {
                    "description": "Type; 0: Once, 1: repeat(epoch, interval)",
                    "type": "integer"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpRspCluster": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpRspService": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "cluster_uuid": {
                    "description": "클러스터 UUID",
                    "type": "string"
                },
                "epoch": {
                    "description": "Epoch -1: infinite, 0 :",
                    "type": "integer"
                },
                "interval": {
                    "description": "Interval",
                    "type": "integer"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "status": {
                    "description": "Status",
                    "type": "integer"
                },
                "step_count": {
                    "description": "스탭 카운트",
                    "type": "integer"
                },
                "step_position": {
                    "description": "스탭 Position",
                    "type": "integer"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ServiceStep"
                    }
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "type": {
                    "description": "Type; 0: Once, 1: repeat(epoch, interval)",
                    "type": "integer"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpRspServiceStep": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "args": {
                    "description": "arguments",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ended": {
                    "description": "Started 스탭 완료 시간",
                    "type": "string"
                },
                "method": {
                    "description": "메소드",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "sequence": {
                    "description": "순서",
                    "type": "integer"
                },
                "service_uuid": {
                    "description": "서비스 Uuid",
                    "type": "string"
                },
                "srated": {
                    "description": "Started 스탭 시작 시간",
                    "type": "string"
                },
                "status": {
                    "description": "Status 상태",
                    "type": "integer"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.HttpRspTemplate": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "commands": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.TemplateCommand"
                    }
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "origin": {
                    "description": "origin\n@example: predefined, userdefined",
                    "type": "string"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.ServiceStep": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "args": {
                    "description": "arguments",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ended": {
                    "description": "Started 스탭 완료 시간",
                    "type": "string"
                },
                "method": {
                    "description": "메소드",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "result": {
                    "description": "Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')",
                    "type": "string"
                },
                "sequence": {
                    "description": "순서",
                    "type": "integer"
                },
                "service_uuid": {
                    "description": "서비스 Uuid",
                    "type": "string"
                },
                "srated": {
                    "description": "Started 스탭 시작 시간",
                    "type": "string"
                },
                "status": {
                    "description": "Status 상태",
                    "type": "integer"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        },
        "v1.TemplateCommand": {
            "type": "object",
            "properties": {
                "api_version": {
                    "description": "api version",
                    "type": "string"
                },
                "args": {
                    "description": "arguments",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "description": "메소드\n@example: \"kubernetes.deployment.get.v1\", \"kubernetes.pod.list.v1\"",
                    "type": "string"
                },
                "name": {
                    "description": "label name",
                    "type": "string"
                },
                "sequence": {
                    "description": "순서",
                    "type": "integer"
                },
                "summary": {
                    "description": "label summary",
                    "type": "string"
                },
                "template_uuid": {
                    "description": "템플릿 UUID",
                    "type": "string"
                },
                "uuid": {
                    "description": "UUID",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "SUDORY",
	Description: "this is a sudory server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
