definitions:
  v1.HttpReqService:
    properties:
      api_version:
        description: api version
        type: string
      cluster_uuid:
        description: 클러스터 UUID
        type: string
      epoch:
        description: 'Epoch -1: infinite, 0 :'
        type: integer
      interval:
        description: Interval
        type: integer
      name:
        description: label name
        type: string
      status:
        description: Status
        type: integer
      step_count:
        description: 스탭 카운트
        type: integer
      step_position:
        description: 스탭 Position
        type: integer
      summary:
        description: label summary
        type: string
      type:
        description: 'Type; 0: Once, 1: repeat(epoch, interval)'
        type: integer
      uuid:
        description: UUID
        type: string
    type: object
  v1.HttpReqServiceStep:
    properties:
      api_version:
        description: api version
        type: string
      args:
        additionalProperties:
          type: string
        description: arguments
        type: object
      ended:
        description: Started 스탭 완료 시간
        type: string
      method:
        description: 메소드
        type: string
      name:
        description: label name
        type: string
      result:
        description: Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')
        type: string
      sequence:
        description: 순서
        type: integer
      service_uuid:
        description: 서비스 Uuid
        type: string
      srated:
        description: Started 스탭 시작 시간
        type: string
      status:
        description: Status 상태
        type: integer
      summary:
        description: label summary
        type: string
      uuid:
        description: UUID
        type: string
    type: object
  v1.HttpReqTemplate:
    properties:
      api_version:
        description: api version
        type: string
      name:
        description: label name
        type: string
      origin:
        description: |-
          origin
          @example: predefined, userdefined
        type: string
      summary:
        description: label summary
        type: string
      uuid:
        description: UUID
        type: string
    type: object
  v1.HttpReqTemplateCommand:
    properties:
      api_version:
        description: api version
        type: string
      args:
        additionalProperties:
          type: string
        description: arguments
        type: object
      method:
        description: |-
          메소드
          @example: "kubernetes.deployment.get.v1", "kubernetes.pod.list.v1"
        type: string
      name:
        description: label name
        type: string
      sequence:
        description: 순서
        type: integer
      summary:
        description: label summary
        type: string
      template_uuid:
        description: 템플릿 UUID
        type: string
      uuid:
        description: UUID
        type: string
    type: object
  v1.HttpRspService:
    properties:
      api_version:
        description: api version
        type: string
      cluster_uuid:
        description: 클러스터 UUID
        type: string
      epoch:
        description: 'Epoch -1: infinite, 0 :'
        type: integer
      interval:
        description: Interval
        type: integer
      name:
        description: label name
        type: string
      status:
        description: Status
        type: integer
      step_count:
        description: 스탭 카운트
        type: integer
      step_position:
        description: 스탭 Position
        type: integer
      steps:
        items:
          $ref: '#/definitions/v1.ServiceStep'
        type: array
      summary:
        description: label summary
        type: string
      type:
        description: 'Type; 0: Once, 1: repeat(epoch, interval)'
        type: integer
      uuid:
        description: UUID
        type: string
    type: object
  v1.HttpRspServiceStep:
    properties:
      api_version:
        description: api version
        type: string
      args:
        additionalProperties:
          type: string
        description: arguments
        type: object
      ended:
        description: Started 스탭 완료 시간
        type: string
      method:
        description: 메소드
        type: string
      name:
        description: label name
        type: string
      result:
        description: Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')
        type: string
      sequence:
        description: 순서
        type: integer
      service_uuid:
        description: 서비스 Uuid
        type: string
      srated:
        description: Started 스탭 시작 시간
        type: string
      status:
        description: Status 상태
        type: integer
      summary:
        description: label summary
        type: string
      uuid:
        description: UUID
        type: string
    type: object
  v1.HttpRspTemplate:
    properties:
      api_version:
        description: api version
        type: string
      name:
        description: label name
        type: string
      origin:
        description: |-
          origin
          @example: predefined, userdefined
        type: string
      summary:
        description: label summary
        type: string
      uuid:
        description: UUID
        type: string
    type: object
  v1.ServiceStep:
    properties:
      api_version:
        description: api version
        type: string
      args:
        additionalProperties:
          type: string
        description: arguments
        type: object
      ended:
        description: Started 스탭 완료 시간
        type: string
      method:
        description: 메소드
        type: string
      name:
        description: label name
        type: string
      result:
        description: Result 스탭 실행 결과(정상:'결과', 오류:'오류 메시지')
        type: string
      sequence:
        description: 순서
        type: integer
      service_uuid:
        description: 서비스 Uuid
        type: string
      srated:
        description: Started 스탭 시작 시간
        type: string
      status:
        description: Status 상태
        type: integer
      summary:
        description: label summary
        type: string
      uuid:
        description: UUID
        type: string
    type: object
info:
  contact:
    email: jaehoon@nexclipper.io
    url: https://nexclipper.io
  description: this is a sudory server.
  title: SUDORY
  version: 0.0.1
paths:
  /client/service:
    get:
      consumes:
      - application/json
      description: Get a Servicies
      parameters:
      - description: Service 의 ClusterUuid
        in: query
        name: cluster_uuid
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.HttpRspService'
            type: array
      tags:
      - server
  /client/service/{service_uuid}/step/{uuid}:
    put:
      consumes:
      - application/json
      description: Update a Service Step
      parameters:
      - description: ServiceStep 의 Uuid
        in: path
        name: service_uuid
        required: true
        type: string
      - description: ServiceStep 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      - description: HttpReqServiceStep
        in: body
        name: step
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqServiceStep'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/service:
    get:
      consumes:
      - application/json
      description: Get a Servicies
      parameters:
      - description: Service 의 ClusterUuid
        in: query
        name: cluster_uuid
        type: string
      - description: Service 의 Uuid
        in: query
        name: uuid
        type: string
      - description: Service 의 Status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.HttpRspService'
            type: array
      tags:
      - server
    post:
      consumes:
      - application/json
      description: Create a Service
      parameters:
      - description: HttpReqService
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqService'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/service/{service_uuid}/step:
    get:
      consumes:
      - application/json
      description: Get a Service Step
      parameters:
      - description: ServiceStep 의 service_uuid
        in: path
        name: service_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.HttpRspServiceStep'
            type: array
      tags:
      - server
    post:
      consumes:
      - application/json
      description: Create a Service Step
      parameters:
      - description: ServiceStep 의 service_uuid
        in: path
        name: service_uuid
        required: true
        type: string
      - description: HttpReqServiceStep
        in: body
        name: step
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqServiceStep'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/service/{service_uuid}/step/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete a Service
      parameters:
      - description: ServiceStep 의 service_uuid
        in: path
        name: service_uuid
        required: true
        type: string
      - description: ServiceStep 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
    get:
      consumes:
      - application/json
      description: Get a Service Step
      parameters:
      - description: ServiceStep 의 service_uuid
        in: path
        name: service_uuid
        required: true
        type: string
      - description: ServiceStep 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.HttpRspServiceStep'
      tags:
      - server
    put:
      consumes:
      - application/json
      description: Update a Service Step
      parameters:
      - description: ServiceStep 의 service_uuid
        in: path
        name: service_uuid
        required: true
        type: string
      - description: ServiceStep 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      - description: HttpReqServiceStep
        in: body
        name: step
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqServiceStep'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/service/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete a Service
      parameters:
      - description: Service 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
    get:
      consumes:
      - application/json
      description: Get a Service
      parameters:
      - description: Service 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.HttpRspService'
      tags:
      - server
    put:
      consumes:
      - application/json
      description: Update a Service
      parameters:
      - description: Service 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      - description: HttpReqService
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqService'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/template:
    get:
      consumes:
      - application/json
      description: Find []template
      parameters:
      - description: Template 의 Uuid
        in: query
        name: uuid
        type: string
      - description: Template 의 Name
        in: query
        name: name
        type: string
      - description: Template 의 Origin
        in: query
        name: origin
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.HttpRspTemplate'
            type: array
      tags:
      - server
    post:
      consumes:
      - application/json
      description: Create a template
      parameters:
      - description: HttpReqTemplate
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqTemplate'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/template/{template_uuid}/command:
    get:
      consumes:
      - application/json
      description: Get a template command
      parameters:
      - description: HttpReqTemplate 의 Uuid
        in: path
        name: template_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.HttpRspTemplate'
            type: array
      tags:
      - server
    post:
      consumes:
      - application/json
      description: Create a template command
      parameters:
      - description: HttpReqTemplate 의 Uuid
        in: path
        name: template_uuid
        required: true
        type: string
      - description: HttpReqTemplateCommand
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqTemplateCommand'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/template/{template_uuid}/command/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete a template command
      parameters:
      - description: HttpReqTemplate 의 Uuid
        in: path
        name: template_uuid
        required: true
        type: string
      - description: HttpReqTemplateCommand 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
    get:
      consumes:
      - application/json
      description: Get a template command
      parameters:
      - description: HttpReqTemplate 의 Uuid
        in: path
        name: template_uuid
        required: true
        type: string
      - description: HttpReqTemplateCommand 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.HttpRspTemplate'
      tags:
      - server
    put:
      consumes:
      - application/json
      description: Update a template command
      parameters:
      - description: HttpReqTemplateCommand 의 TemplateUuid
        in: path
        name: template_uuid
        required: true
        type: string
      - description: HttpReqTemplateCommand 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      - description: HttpReqTemplateCommand
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqTemplateCommand'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
  /server/template/{uuid}:
    delete:
      consumes:
      - application/json
      description: Delete a template
      parameters:
      - description: Template 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
    get:
      consumes:
      - application/json
      description: Get a template
      parameters:
      - description: Template 의 Uuid
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.HttpRspTemplate'
      tags:
      - server
    put:
      consumes:
      - application/json
      description: Update a template
      parameters:
      - description: HttpReqTemplate
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/v1.HttpReqTemplate'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      tags:
      - server
swagger: "2.0"
