events:
  - event:
    name: 'client poll'
    pattern: '/client/poll'
    listeners:
    # - listener:
    #   type: 'webhook'
    #   method: post
    #   url: 'http://localhost:8000/'
    #   content-type: 'application/json'
    #   timeout: 30  
    # - listener: 
    #   type: 'file'
    #   path: ./log/server.log
  - event:
    name: 'client --all'
    pattern: '/client/*'
    buzy-timeout: 15
    listeners:
    - listener:
      type: 'webhook'
      method: post
      url: 'http://localhost:8000/'
      content-type: 'application/json'
      timeout: 30
    # - listener: 
    #   type: 'file'
    #   path: ./log/client-auth.log
  - event:
    name: 'client-auth'
    pattern: '/client/auth'
    listeners:
    # - listener:
    #   type: 'webhook'
    #   method: post
    #   url: 'http://localhost:8000/'
    #   content-type: 'application/json'
    #   timeout: 30
    # - listener: 
    #   type: 'file'
    #   path: ./log/client-auth(1).log
    # - listener: 
    #   type: 'file'
    #   path: ./log/client-auth.log