// Code generated by Ice-cream-maker DO NOT EDIT.
package v2
 
func (Template) ColumnNames() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"origin",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (TemplateCommand) ColumnNames() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"template_uuid",
 		"sequence",
 		"method",
 		"args",
 		"result_filter",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (Template) ColumnNamesWithAlias() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"origin",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (TemplateCommand) ColumnNamesWithAlias() []string {
	return []string{
 		"id",
 		"uuid",
 		"name",
 		"summary",
 		"template_uuid",
 		"sequence",
 		"method",
 		"args",
 		"result_filter",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (row Template) Values() []interface{} {
	return []interface{}{
		row.Id,
		row.Uuid,
		row.Name,
		row.Summary,
		row.Origin,
		row.Created,
		row.Updated,
		row.Deleted,
	}
}
 
func (row TemplateCommand) Values() []interface{} {
	return []interface{}{
		row.Id,
		row.Uuid,
		row.Name,
		row.Summary,
		row.TemplateUuid,
		row.Sequence,
		row.Method,
		row.Args,
		row.ResultFilter,
		row.Created,
		row.Updated,
		row.Deleted,
	}
}

type Scanner interface {
	Scan(dest ...interface{}) error
}
 
func (row *Template) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.Id,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.Origin,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	)
}
 
func (row *TemplateCommand) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.Id,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.TemplateUuid,
		&row.Sequence,
		&row.Method,
		&row.Args,
		&row.ResultFilter,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	)
}
 
func (row *Template) Ptrs() []interface{} {
	return []interface{}{
		&row.Id,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.Origin,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	}
}
 
func (row *TemplateCommand) Ptrs() []interface{} {
	return []interface{}{
		&row.Id,
		&row.Uuid,
		&row.Name,
		&row.Summary,
		&row.TemplateUuid,
		&row.Sequence,
		&row.Method,
		&row.Args,
		&row.ResultFilter,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	}
}
