// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package event

import (
	"fmt"
	"strings"
)

const (
	// NotifierTypeConsol is a NotifierType of type Consol.
	NotifierTypeConsol NotifierType = iota
	// NotifierTypeWebhook is a NotifierType of type Webhook.
	NotifierTypeWebhook
	// NotifierTypeFile is a NotifierType of type File.
	NotifierTypeFile
	// NotifierTypeRabbitMQ is a NotifierType of type RabbitMQ.
	NotifierTypeRabbitMQ
)

const _NotifierTypeName = "consolwebhookfilerabbitMQ"

var _NotifierTypeNames = []string{
	_NotifierTypeName[0:6],
	_NotifierTypeName[6:13],
	_NotifierTypeName[13:17],
	_NotifierTypeName[17:25],
}

// NotifierTypeNames returns a list of possible string values of NotifierType.
func NotifierTypeNames() []string {
	tmp := make([]string, len(_NotifierTypeNames))
	copy(tmp, _NotifierTypeNames)
	return tmp
}

var _NotifierTypeMap = map[NotifierType]string{
	NotifierTypeConsol:   _NotifierTypeName[0:6],
	NotifierTypeWebhook:  _NotifierTypeName[6:13],
	NotifierTypeFile:     _NotifierTypeName[13:17],
	NotifierTypeRabbitMQ: _NotifierTypeName[17:25],
}

// String implements the Stringer interface.
func (x NotifierType) String() string {
	if str, ok := _NotifierTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("NotifierType(%d)", x)
}

var _NotifierTypeValue = map[string]NotifierType{
	_NotifierTypeName[0:6]:                    NotifierTypeConsol,
	strings.ToLower(_NotifierTypeName[0:6]):   NotifierTypeConsol,
	_NotifierTypeName[6:13]:                   NotifierTypeWebhook,
	strings.ToLower(_NotifierTypeName[6:13]):  NotifierTypeWebhook,
	_NotifierTypeName[13:17]:                  NotifierTypeFile,
	strings.ToLower(_NotifierTypeName[13:17]): NotifierTypeFile,
	_NotifierTypeName[17:25]:                  NotifierTypeRabbitMQ,
	strings.ToLower(_NotifierTypeName[17:25]): NotifierTypeRabbitMQ,
}

// ParseNotifierType attempts to convert a string to a NotifierType.
func ParseNotifierType(name string) (NotifierType, error) {
	if x, ok := _NotifierTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _NotifierTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return NotifierType(0), fmt.Errorf("%s is not a valid NotifierType, try [%s]", name, strings.Join(_NotifierTypeNames, ", "))
}
