client:
  enabled: true
  image: "repo.nexclipper.io/nexclipper-dev/nexclipper-sudory-client:latest"
  environment_variable:
    data:
      server: "" #http://<IP>:<PORT>
      clusterid: ""
      token: ""

server:
  enabled: false
  image: "repo.nexclipper.io/nexclipper-dev/nexclipper-sudory-server:latest"
  containerPort: 8099
  environment_variable:
    data:
      SUDORY_DB_HOST: "ncdb-mariadb-primary.mariadb.svc.cluster.local"
      SUDORY_DB_PORT: "3306"
      SUDORY_DB_SCHEME: "nc_sudory"
      SUDORY_DB_EXPORT_PATH: "."
      SUDORY_DB_SERVER_USERNAME: "user"
      SUDORY_LOG_SEVERITY: "info"
      SUDORY_LOG_SYSTEM_EVENT: "false"
      SUDORY_LOG_VERBOSE: "true"
      SUDORY_LOG_VERBOSELEVEL: "9"
      SUDORY_LOG_FILENAME: "./sudory.log"
      SUDORY_LOG_MAXSIZE: "10"
      SUDORY_LOG_MAXAGE: "5"
      SUDORY_LOG_MAXBACKUPS: "10"
      SUDORY_LOG_COMPRESS: "false"
  secret_variable:
    data:
      db_server_password: ""

  serverrule:
    enabled: false
    data:
     enigma.yml: |
       enigma:
         sudory.default.crypto:
           block-method: none
           block-size: 0
           block-key:
           cipher-mode: none
           cipher-salt: null
           padding: none
           strconv: plain

