// Code generated by Ice-cream-maker DO NOT EDIT.
package v2
 
func (ClusterToken_property) ColumnNames() []string {
	return []string{
 		"name",
 		"summary",
 		"cluster_uuid",
 		"token",
 		"issued_at_time",
 		"expiration_time",
	}
}
 
func (ClusterToken) ColumnNames() []string {
	return []string{
 		"name",
 		"summary",
 		"cluster_uuid",
 		"token",
 		"issued_at_time",
 		"expiration_time",
 		"id",
 		"uuid",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (ClusterToken_property) ColumnNamesWithDefault() []string {
	return []string{
 		"name",
 		"summary",
 		"cluster_uuid",
 		"token",
 		"issued_at_time",
 		"expiration_time",
	}
}
 
func (ClusterToken) ColumnNamesWithDefault() []string {
	return []string{
 		"name",
 		"summary",
 		"cluster_uuid",
 		"token",
 		"issued_at_time",
 		"expiration_time",
 		"id",
 		"uuid",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (ClusterToken_property) ColumnNamesWithAlias() []string {
	return []string{
 		"name",
 		"summary",
 		"cluster_uuid",
 		"token",
 		"issued_at_time",
 		"expiration_time",
	}
}
 
func (ClusterToken) ColumnNamesWithAlias() []string {
	return []string{
 		"name",
 		"summary",
 		"cluster_uuid",
 		"token",
 		"issued_at_time",
 		"expiration_time",
 		"id",
 		"uuid",
 		"created",
 		"updated",
 		"deleted",
	}
}
 
func (row ClusterToken_property) Values() []interface{} {
	return []interface{}{
		row.Name,
		row.Summary,
		row.ClusterUuid,
		row.Token,
		row.IssuedAtTime,
		row.ExpirationTime,
	}
}
 
func (row ClusterToken) Values() []interface{} {
	return []interface{}{
		row.Name,
		row.Summary,
		row.ClusterUuid,
		row.Token,
		row.IssuedAtTime,
		row.ExpirationTime,
		row.ID,
		row.Uuid,
		row.Created,
		row.Updated,
		row.Deleted,
	}
}

type Scanner interface {
	Scan(dest ...interface{}) error
}
 
func (row *ClusterToken_property) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.Name,
		&row.Summary,
		&row.ClusterUuid,
		&row.Token,
		&row.IssuedAtTime,
		&row.ExpirationTime,
	)
}
 
func (row *ClusterToken) Scan(scanner Scanner) error {
	return scanner.Scan(
		&row.Name,
		&row.Summary,
		&row.ClusterUuid,
		&row.Token,
		&row.IssuedAtTime,
		&row.ExpirationTime,
		&row.ID,
		&row.Uuid,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	)
}
 
func (row *ClusterToken_property) Ptrs() []interface{} {
	return []interface{}{
		&row.Name,
		&row.Summary,
		&row.ClusterUuid,
		&row.Token,
		&row.IssuedAtTime,
		&row.ExpirationTime,
	}
}
 
func (row *ClusterToken) Ptrs() []interface{} {
	return []interface{}{
		&row.Name,
		&row.Summary,
		&row.ClusterUuid,
		&row.Token,
		&row.IssuedAtTime,
		&row.ExpirationTime,
		&row.ID,
		&row.Uuid,
		&row.Created,
		&row.Updated,
		&row.Deleted,
	}
}
