definitions:
  model.ReqCluster:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /cluster:
    post:
      consumes:
      - application/json
      description: Create a Cluster
      parameters:
      - description: Cluster의 정보
        in: body
        name: namespace
        required: true
        schema:
          $ref: '#/definitions/model.ReqCluster'
      produces:
      - application/json
      responses:
        "200":
          description: ""
swagger: "2.0"
