definitions:
  model.Catalogue:
    properties:
      name:
        type: string
    type: object
  model.Catalogues:
    properties:
      items:
        items:
          $ref: '#/definitions/model.Catalogue'
        type: array
    type: object
  model.Cluster:
    properties:
      created:
        type: string
      id:
        type: string
      name:
        type: string
      updated:
        type: string
    type: object
  model.ReqCluster:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /catalogue:
    get:
      description: Get a Catalogues
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Catalogues'
  /cluster:
    post:
      consumes:
      - application/json
      description: Create a Cluster
      parameters:
      - description: Cluster의 정보
        in: body
        name: namespace
        required: true
        schema:
          $ref: '#/definitions/model.ReqCluster'
      produces:
      - application/json
      responses:
        "200":
          description: ""
  /cluster/{id}:
    get:
      consumes:
      - application/json
      description: Get a Cluster
      parameters:
      - description: Cluster의 ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Cluster'
swagger: "2.0"
