package ice_cream_maker

import (
	"bytes"
	"strings"
	"text/template"
)

func PrintWarning(objs ...interface{}) (s string, err error) {
	tmpl := TemplatePrintWarning{Warning: []string{
		"Code generated by Ice-cream-maker DO NOT EDIT.",
	}}

	tmpl_, err := template.New("print_warning.go").Parse(strings.TrimSpace(tmpl.Text()))
	if err != nil {
		return
	}

	buf := bytes.Buffer{}
	if err = tmpl_.Execute(&buf, tmpl); err != nil {
		return
	}

	s = buf.String()
	return
}

type TemplatePrintWarning struct {
	Warning []string
	// Discriptors []TemplateColumnPackageDiscriptor
}

func (TemplatePrintWarning) Text() string {
	return `
{{ range $index, $warn := .Warning -}} 
// {{ $warn }}
{{ end }}
`
}
